name: HerokuDeploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "wgo-opengar-api" #Must be unique in Heroku
          heroku_email: "info@wisegar.org"
          appdir: "wgo-opengar-core" # <- This will point to the api folder in your project
